In [33]:
from scipy import sparse
import numpy as np

# Generate A
n = 3
B = sparse.diags(np.ones(n)*-4) + sparse.diags(np.ones(n-1), -1) + sparse.diags(np.ones(n-1), 1)
diags = []
for i in range(n):
    diags.append(B)
A = sparse.block_diag(diags)
A = A + sparse.diags(np.ones(n**2 - n), n) + sparse.diags(np.ones(n**2 - n), -(n))
#Generate b
b = np.zeros(n)
b[0] = -100
b[n-1] = -100
b = np.tile(b, n)

In [34]:
print(B.toarray())
print(B)

[[-4.  1.  0.]
 [ 1. -4.  1.]
 [ 0.  1. -4.]]
  (0, 0)	-4.0
  (0, 1)	1.0
  (1, 0)	1.0
  (1, 1)	-4.0
  (1, 2)	1.0
  (2, 1)	1.0
  (2, 2)	-4.0


In [35]:
print(sparse.diags(np.ones(2),1).toarray())

[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]


In [36]:
print(sparse.diags(np.ones(5),5).toarray())

[[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


In [37]:
print(A.toarray())

[[-4.  1.  0.  1.  0.  0.  0.  0.  0.]
 [ 1. -4.  1.  0.  1.  0.  0.  0.  0.]
 [ 0.  1. -4.  0.  0.  1.  0.  0.  0.]
 [ 1.  0.  0. -4.  1.  0.  1.  0.  0.]
 [ 0.  1.  0.  1. -4.  1.  0.  1.  0.]
 [ 0.  0.  1.  0.  1. -4.  0.  0.  1.]
 [ 0.  0.  0.  1.  0.  0. -4.  1.  0.]
 [ 0.  0.  0.  0.  1.  0.  1. -4.  1.]
 [ 0.  0.  0.  0.  0.  1.  0.  1. -4.]]


In [ ]:
import matplotlib.pyplot as plt
import numpy as np

def problem6(n, omega, tol = 1e-8, maxiters = 100, plot = False):
    B = sparse.diags(np.ones(n)*-4) + sparse.diags(np.ones(n-1), -1) + sparse.diags(np.ones(n-1), 1)
    diags = []
    for i in range(n):
        diags.append(B)
    A = sparse.block_diag(diags)
    A = A + sparse.diags(np.ones(n**2 - n), n) + sparse.diags(np.ones(n**2 - n), -(n))
    b = np.zeros(n)
    b[0] = -100
    b[n-1] = -100
    b = np.tile(b, n)
    u = problem5(A, b, omega, tol, maxiters) #replace problem5 with function name to problem 5
    
    if plot == False:
        return u, u[1] #i'm assuming the number of iterations taken is in index 1 of what prob 5 returns
    
    if plot == True:
        umat = u.reshape((n,n))
        X = np.arange(1, n+1, 1) 
        Y = np.arange(1, n+1, 1)
        xx, yy = np.meshgrid(X,Y)
        plt.pcolormesh(xx, yy, umat, cmap = "coolwarm") #if this doesn't work, change xx and yy to X and Y
        plt.title("Heatmap of Plate's Temperature in Steady State")
        plt.colorbar()
        plt.show()
        return u, u[1]
    

In [40]:
def problem7():
    omegavec = np.arange(1, 2, 0.05)
    n = 20
    solnvec = np.zeros((len(omegavec),1))
    itervec = np.zeros((len(omegavec),1))
    for i in range(len(omegavec)):
        solnvec[i] = problem6(n, omegavec[i], tol = 1e-2, maxiters = 1000, plot = False)[0]
        itervec[i] = problem6(n, omegavec[i], tol = 1e-2, maxiters = 1000, plot = False)[1]
    plt.plot(omegavec, itervec)
    plt.xlabel("Omega")
    plt.ylabel("Number of Iterations")
    plt.title("Number of Iterations as a Function of Omega")
    plt.show()
    a = np.array([1,2,3,4,5,1,6,1]) 
    minindex = np.argmin(itervec)
    
    return omegavec[minindex]

[1 2 3]


In [42]:
omegavec = np.arange(1, 2, 0.05)
print(omegavec)


[ 1.    1.05  1.1   1.15  1.2   1.25  1.3   1.35  1.4   1.45  1.5   1.55
  1.6   1.65  1.7   1.75  1.8   1.85  1.9   1.95]
